name = "Preconditioners"
uuid = "af69fa37-3177-5a40-98ee-561f696e4fcd"
version = "0.3.2"

[deps]
AlgebraicMultigrid = "2169fc97-5a83-5252-b627-83903c6c433c"
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
LimitedLDLFactorizations = "f5a24dde-3ab7-510b-b81b-6a72c6098d3b"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
julia = "1"
AlgebraicMultigrid = "0.1, 0.2, 0.3, 0.4"
Compat = "1, 2, 3"
LimitedLDLFactorizations = "0.1, 0.2, 0.3"

[extras]
IterativeSolvers = "42fd0dbc-a981-5370-80f2-aaf504508153"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["IterativeSolvers", "Random", "Test"]
